services:
  postgres:
    image: postgres:15-alpine
    container_name: nds_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Teju4630
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nds_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: nds_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teju4630
      - POSTGRES_DB=notification_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_MOCK_EMAIL=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: nds_worker
    command: python -m app.worker.main
    environment:
      - ENVIRONMENT=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teju4630
      - POSTGRES_DB=notification_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_MOCK_EMAIL=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: nds_seed
    command: python -m app.scripts.seed_data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Teju4630
      - POSTGRES_DB=notification_db
    depends_on:
      api:
        condition: service_started
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: nds_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api

volumes:
  postgres_data:
